identity:
  name: Paw
  username: hujiyo
  honey: 老公
tool_execution:
  mode: threaded
  timeout: 30.0
api:
  key: ca01c1d55ef643fa90e7d6addba27a12.lJBRo8JGjdwYyxCH
  url: https://open.bigmodel.cn/api/coding/paas/v4/chat/completions
  model: glm-4.7
memory:
  enabled: false
  embedding_url: http://localhost:1234/v1/embeddings
  embedding_key: ''
  embedding_model: text-embedding-qwen3-embedding-0.6b
recall:
  enabled: true
  threshold: 0.36
terminal:
  shell: powershell
  encoding: utf-8
  buffer_size: 24
web:
  search_engine: duckduckgo
  max_results: 5
  page_size: 4096
  use_jina_reader: true
system:
  home_dir: D:\桌面\Paw
  chunk_size: 96000
theme:
  id: yaoye
  titlebar: '#000000'
  loading: '#000000'
  main: '#000000'
  accent: '#FF9E80'
